Added virtual function `uca_camera_grab_live`
ufo-kit/libuca pull request #97
Opened 2023-10-25 12:54 UTC by gabs1234

Nothing special in the implementation. Everything is the same as `uca_camera_grab`.

2023-10-26 07:46 UTC, tfarago requested changes
Except the duplication good.

2023-10-26 07:46 UTC, tfarago commented on plugins/mock/uca-mock-camera.c
> +uca_mock_camera_grab_live (UcaCamera *camera, gpointer data, GError **error)
Can you make one function which is called from both, the normal `grab` and `grab_live` instead of duplicating code?

2023-10-26 07:46 UTC, tfarago commented on src/uca-camera.c
> +uca_camera_grab_live (UcaCamera *camera, gpointer data, GError **error)
same here.

2025-01-14 10:20 UTC, gabs1234 commented
This function is no longer relevant, as the images on the phantom camera are now being pulled as soon as they're available.

2025-01-14 10:20 UTC, closed without merging